# Generated by Django 4.0.4 on 2022-07-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='parent_book',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookLog',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
